output "environment" {
  description = "Environment label."
  value       = var.environment
}

output "product_ids" {
  description = "Stripe product IDs."
  value = {
    starter = stripe_product.starter.id
    pro     = stripe_product.pro.id
  }
}

output "price_ids" {
  description = "Stripe price IDs for all paid plans."
  value = {
    starter_monthly = stripe_price.starter_monthly.id
    starter_yearly  = stripe_price.starter_yearly.id
    pro_monthly     = stripe_price.pro_monthly.id
    pro_yearly      = stripe_price.pro_yearly.id
  }
}

output "payment_link_urls" {
  description = "Stripe Payment Link URLs for checkout buttons."
  value = {
    starter_monthly = data.external.payment_links.result.starter_monthly_url
    starter_yearly  = data.external.payment_links.result.starter_yearly_url
    pro_monthly     = data.external.payment_links.result.pro_monthly_url
    pro_yearly      = data.external.payment_links.result.pro_yearly_url
  }
}

output "webhook_endpoint_id" {
  description = "Stripe webhook endpoint ID (null when webhooks disabled)."
  value       = try(stripe_webhook_endpoint.billing[0].id, null)
}

output "webhook_secret" {
  description = "Stripe webhook signing secret for STRIPE_WEBHOOK_SECRET."
  value       = try(stripe_webhook_endpoint.billing[0].secret, null)
  sensitive   = true
}

output "env_vars" {
  description = "Zoomify .env keys produced by this module (STRIPE_SECRET_KEY is not managed here)."
  sensitive   = true
  value = {
    STRIPE_LINK_STARTER_MONTHLY = data.external.payment_links.result.starter_monthly_url
    STRIPE_LINK_STARTER_YEARLY  = data.external.payment_links.result.starter_yearly_url
    STRIPE_LINK_PRO_MONTHLY     = data.external.payment_links.result.pro_monthly_url
    STRIPE_LINK_PRO_YEARLY      = data.external.payment_links.result.pro_yearly_url
    STRIPE_WEBHOOK_SECRET       = try(stripe_webhook_endpoint.billing[0].secret, null)
  }
}

output "env_file_content" {
  description = "Ready-to-append snippet for the root .env file."
  sensitive   = true
  value       = <<-EOT
    # Generated by terraform (${var.environment}) — STRIPE_SECRET_KEY must be set separately
    STRIPE_LINK_STARTER_MONTHLY=${data.external.payment_links.result.starter_monthly_url}
    STRIPE_LINK_STARTER_YEARLY=${data.external.payment_links.result.starter_yearly_url}
    STRIPE_LINK_PRO_MONTHLY=${data.external.payment_links.result.pro_monthly_url}
    STRIPE_LINK_PRO_YEARLY=${data.external.payment_links.result.pro_yearly_url}
    STRIPE_WEBHOOK_SECRET=${try(stripe_webhook_endpoint.billing[0].secret, "use_stripe_listen_for_local_dev")}
  EOT
}
